const jobs = [
    {
      title: "Senior UX Designer",
      image: "/api/placeholder/48/48",
      type: "Contract Base",
      location: "Jakarta",
      payment: "$30K-$35K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
    {
      title: "Software Engineer",
      image: "/api/placeholder/48/48",
      type: "Full Time",
      location: "Surabaya",
      payment: "$50K-$60K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
    {
      title: "Junior Graphic Designer",
      image: "/api/placeholder/48/48",
      type: "Full Time",
      location: "Malang",
      payment: "$50K-$70K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
    {
      title: "Product Designer",
      image: "/api/placeholder/48/48",
      type: "Full Time",
      location: "Bandung",
      payment: "$35K-$40K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
    {
      title: "Marketing Officer",
      image: "/api/placeholder/48/48",
      type: "Internship",
      location: "Jakarta",
      payment: "$50K-$90K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
    {
      title: "Interaction Designer",
      image: "/api/placeholder/48/48",
      type: "Full Time",
      location: "Malang",
      payment: "$5K-$10K",
      deadline: "4 Days Remaining",
      bookmarked: false,
    },
  ];

export default jobs;